# Generated by Django 4.2.4 on 2023-09-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gbc_crm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department name')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Supervisor's First name")),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Supervisor's Last name")),
                ('email_address', models.CharField(blank=True, max_length=50, null=True, verbose_name="Supervisor's Email Address")),
                ('date_of_birth', models.DateField(default='')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=gbc_crm.models.Department, to='gbc_crm.department')),
            ],
            options={
                'verbose_name_plural': 'Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inventory name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Inventory Description')),
                ('procured_date', models.DateTimeField(auto_now_add=True, verbose_name='Inventory Date Bought')),
                ('date_maintained', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inventory Date Maintained')),
                ('price', models.CharField(max_length=10, verbose_name='Inventory price')),
                ('departments_to_use', models.ManyToManyField(to='gbc_crm.department')),
                ('supervisor_responsible', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Last Name')),
                ('email_address', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email Address')),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('date_of_birth', models.DateField(default='')),
                ('date_employed', models.DateField(default='', verbose_name='Date Employed')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_department', to='gbc_crm.department')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_supervisor', to='gbc_crm.supervisor')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
