# Generated by Django 4.2.4 on 2023-08-30 16:59

from django.db import migrations, models
import django.db.models.deletion
import gbc_crm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department name')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsInvolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments_to_use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.department')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Supervisor's name")),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=gbc_crm.models.Department, to='gbc_crm.department')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inventory name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Inventory Description')),
                ('procured_date', models.DateTimeField(verbose_name='Inventory Date Bought')),
                ('date_maintained', models.DateTimeField(blank=True, null=True, verbose_name='Inventory Date Maintained')),
                ('price', models.CharField(max_length=10, verbose_name='Inventory price')),
                ('departments_to_use', models.ManyToManyField(through='gbc_crm.DepartmentsInvolved', to='gbc_crm.department')),
                ('supervisor_responsible', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Employee Name')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name="Employee's Age")),
                ('date_employed', models.DateField(default='', verbose_name='Date Employed')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.department')),
                ('supervisor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='departmentsinvolved',
            name='inventory_to_be_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbc_crm.inventory'),
        ),
    ]
