# Generated by Django 4.2.4 on 2023-09-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbc_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_supervisor', to='gbc_crm.supervisor'),
        ),
    ]
