# Generated by Django 4.2.4 on 2023-09-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbc_crm', '0002_employee_contact_no_employee_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password_1',
            field=models.CharField(default='', max_length=50, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_2',
            field=models.CharField(default='', max_length=50, verbose_name='Confirm Password'),
        ),
    ]
